version: '3.8'

services:
  postgres-beellage:
    image: postgres:13
    container_name: postgres-beellage
    environment:
      POSTGRES_DB: issue_tracker
      POSTGRES_USER: judy
      POSTGRES_PASSWORD: judy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./beellage-backend-server
      dockerfile: Dockerfile
    container_name: beellage_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-beellage:5432/issue_tracker
      SPRING_DATASOURCE_USERNAME: judy
      SPRING_DATASOURCE_PASSWORD: judy
    ports:
      - "8080:8080"
    depends_on:
      - postgres-beellage

  frontend:
    build:
      context: ./beellage-frontend-server
      dockerfile: Dockerfile
    container_name: beellage_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres
