version: '3.8'

services:
  beellage_db:
    image: postgres:13
    container_name: beellage_db
    environment:
      POSTGRES_DB: issue_tracker
      POSTGRES_USER: judy
      POSTGRES_PASSWORD: judy
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./beellage-backend-server
      dockerfile: Dockerfile
    container_name: beellage_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://beellage_db:5432/issue_tracker
      SPRING_DATASOURCE_USERNAME: judy
      SPRING_DATASOURCE_PASSWORD: judy
    ports:
      - "8080:8080"
    depends_on:
      - beellage_db
    networks:
      - app-network

  frontend:
    build:
      context: ./beellage-frontend-server
      dockerfile: Dockerfile
    container_name: beellage_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
